name: VVV Tweet Bot
on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Run bot
        env:
          API_URL: https://www.vvv.so/api/get-top-collections
          TEXT_TEMPLATE: "New VVV collection: %%NAME%% (%%SIZE%%) — %%URL%%"
          MAX_TWEETS_PER_RUN: "3"
          INCLUDE_COMING_SOON: "false"
          GIST_ID: ${{ secrets.GIST_ID }}
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
          X_API_KEY: ${{ secrets.X_API_KEY }}
          X_API_SECRET: ${{ secrets.X_API_SECRET }}
          X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
          X_ACCESS_SECRET: ${{ secrets.X_ACCESS_SECRET }}
        run: node bot.js
